version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/app
      - /usr
      - /usr/app/node_modules
  event-bus:
    build: event-bus
    ports:
      - '4005:4005'
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules
  latest:
    build: latest
    ports:
      - '4002:4002'
    volumes:
      - ./latest:/usr/app
      - /usr/app/node_modules
  map:
    build: map
    ports:
      - '4000:4000'
    volumes:
      - ./map:/usr/app
      - /usr/app/node_modules
  moderator:
    build: moderator
    ports:
      - '4003:4003'
    volumes:
      - ./moderator:/usr/app
      - /usr/app/node_modules
  notify:
    build: notify
    ports:
      - '4004:4004'
    volumes:
      - ./notify:/usr/app
      - /usr/app/node_modules
  sightings:
    build: sightings
    ports:
      - '4001:4001'
    volumes:
      - ./sightings:/usr/app
      - /usr/app/node_modules
  bigfoot-db:
    image: mongo:latest
    volumes:
      - bigfoot-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  bigfoot-data:

