version: '3.9'
services:
  client:
    build: client
    ports:
      - '3000:3000'
  event-bus:
    build: event-bus
    ports:
      - '4005:4005'
  latest:
    build: latest
    ports:
      - '4002:4002'
  map:
    build: map
    ports:
      - '4000:4000'
  moderator:
    build: moderator
    ports:
      - '4003:4003'
  notify:
    build: notify
    ports:
      - '4004:4004'
  sightings:
    build: sightings
    ports:
      - '4001:4001'
  bigfoot-db:
    image: mongo:latest
    volumes:
      - bigfoot-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret

volumes:
  bigfoot-data:
