module.exports = {
    apps: [{
        name: "client",
        instances: 1,
        exec_mode: "cluster",
        script: "./client/build/index.js",
        args: ""
    }, {
        name: "event-bus",
        instances: 1,
        exec_mode: "cluster",
        script: "./event-bus/index.js",
        args: ""
    }, {
        name: "notify-service",
        instances: 5,
        exec_mode: "cluster",
        script: "./notify/index.js",
        args: ""
    }, {
        name: "moderator-service",
        instances: 5,
        exec_mode: "cluster",
        script: "./moderator/index.js",
        args: ""
    }, {
        name: "latest-service",
        instances: 5,
        exec_mode: "cluster",
        script: "./latest/index.js",
        args: ""
    }, {
        name: "sightings-service",
        instances: 5,
        exec_mode: "cluster",
        script: "./sightings/index.js",
        args: ""
    }, {
        name: "map-service",
        instances: 5,
        exec_mode: "cluster",
        script: "./map/index.js",
        args: ""
    }]
};
